### ISSUE TITLE
SERVIDOR WEB

### ISSUE THREAD

**Issue by xrezu** [AsyncCore/asynccore.github.io#27]
1. APACHE

- [ ] Terminar de configurar el servidor
- [x] Hablar con Masmóvil para CGNAT e IP pública
- [x] Mirar firewall y seguridad para conexiones incoming por 21, 22, 80, 8080, 443 TCP y UDP
- [x] ¿SSL? mirar certificar la web para secure login por https
- [x] ¿Dominio? Mirar redirecciones para un dominio básico desde NOIP (precio?)

2. MYSQL

- [x] Instalar el servidor y realizar una primera configuración.
- [x] Comprobar funcionamiento con script sencillo y queries básicas.
- [x] Comprobar conexión con el exterior para incoming 80.
- [x] Comprobar seguridad administrativa: gestión de claves y ¿tokens? 

3. PHP

- [x] Instalar intérprete PHP y buscar cómo servirlo a Apache.
- [x] Mirar configuración inicial de php.ini para servidores caseros.
- [x] Comprobar incoming 80, 8080 y 443.
- [x] Mirar e instalar módulos? addons? para funcionalidad extra. Librerías ya escritas.

4. SEGURIDAD

- [x] Comprobar seguridad. ¿DDOS? ¿Cloudflare? Rentable? 

5. MISCELÁNEA

¿¿??¿?

**Comment by GyllenhaalSP** [comment]
Completado. Se ha añadido además un proxy reverso con Nginx que sirve ficheros estáticos mientras que apache2 sólo se encarga de recibir, procesar y devolver código PHP. Se han añadido usuarios para todos los componentes del grupo. Se ha añadido un contenedor docker para servir de drop-filesystem. También se ha añadido una wiki y un sitio de mkdocs.
